name: Build SDK

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES_FOLDER: bin/Release/nugets

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build all
        run: dotnet build --configuration release
      - name: Generate packges
        run: dotnet pack --configuration release
      - name: Upload packages
        uses: actions/upload-artifact@master
        with:
          name: packages
          path: ${{ env.NUGET_PACKAGES_FOLDER }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build --configuration release /p:GITHUB_ACTIONS=false
      - name: Test
        id: tests
        continue-on-error: true
        run: |
          dotnet test \
            --configuration release \
            --framework net6.0 \
            --no-build \
            --no-restore \
            --logger "trx;LogFilePrefix=net6.0" \
            --results-directory "${{ github.workspace }}/TestResults" \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:GITHUB_ACTIONS=false
      - name: Check test failure
        if: github.event_name == 'pull_request' && steps.tests.outcome != 'success'
        run: exit 1  
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          flags: net6.0
      - name: Parse Trx files
        uses: NasAmin/trx-parser@v0.2.0
        id: trx-parser
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository # does not work on PRs from forks
        with:
          TRX_PATH: ${{ github.workspace }}/TestResults
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      